#!/bin/bash

echo "🔥 URGENT: Firebase Email Template Configuration"
echo "=============================================="
echo ""
echo "❌ CURRENT ISSUE: You're getting the default Firebase email template"
echo "✅ SOLUTION: Configure Firebase Console to use custom templates"
echo ""

echo "📋 STEP-BY-STEP INSTRUCTIONS:"
echo "------------------------------"
echo ""

echo "1️⃣ GO TO FIREBASE CONSOLE:"
echo "   🔗 https://console.firebase.google.com/project/swift-26949/authentication/emails"
echo ""

echo "2️⃣ CONFIGURE ACTION URL:"
echo "   a) Click 'Settings' tab (next to Templates)"
echo "   b) Scroll down to 'Authorized domains'"
echo "   c) Make sure 'swift-26949.web.app' is in the list"
echo "   d) Click 'Customize action URL' (or 'Advanced' tab)"
echo "   e) Set Action URL to: https://swift-26949.web.app"
echo "   f) Click 'Save'"
echo ""

echo "3️⃣ CUSTOMIZE EMAIL TEMPLATE:"
echo "   a) Go back to 'Templates' tab"
echo "   b) Click 'Password reset'"
echo "   c) Change these settings:"
echo "      - Subject: 'Reset Your ECommerce Admin Password 🔐'"
echo "      - Sender name: 'ECommerce Admin'"
echo "      - Reply-to: your-email@domain.com"
echo "   d) In the template body, you can customize or use default"
echo "   e) Click 'Save'"
echo ""

echo "4️⃣ VERIFY DEPLOYMENT:"
echo "   Our beautiful pages are already deployed at:"
echo "   🌐 https://swift-26949.web.app/reset-password"
echo "   🌐 https://swift-26949.web.app/password_reset.html"
echo ""

echo "5️⃣ TEST THE FLOW:"
echo "   a) Run your Flutter app"
echo "   b) Go to forgot password"
echo "   c) Enter: shahriar12688@gmail.com"
echo "   d) Check email - should now show custom template!"
echo ""

echo "📧 WHAT WILL CHANGE:"
echo "   BEFORE: 'Follow this link to reset your project-370802731084 password'"
echo "   AFTER:  Beautiful branded email with your custom design"
echo ""

echo "⚡ QUICK LINKS:"
echo "   🔧 Firebase Auth Settings: https://console.firebase.google.com/project/swift-26949/authentication/settings"
echo "   📧 Email Templates: https://console.firebase.google.com/project/swift-26949/authentication/emails"
echo "   🌐 Your Custom Page: https://swift-26949.web.app/reset-password"
echo ""

echo "🎯 KEY SETTING TO CHANGE:"
echo "   In Firebase Console → Authentication → Settings → Advanced"
echo "   Set 'Action URL' to: https://swift-26949.web.app"
echo ""

echo "⏰ This should take 2-3 minutes to configure, then test immediately!"

read -p "Press Enter when you've completed the Firebase Console configuration..."

echo ""
echo "🧪 TESTING YOUR SETUP:"
echo "----------------------"
echo "1. Open your Flutter app"
echo "2. Go to forgot password screen"
echo "3. Enter an email and send reset"
echo "4. Check the email - it should now be beautiful! ✨"
echo ""
echo "If you're still seeing the old template:"
echo "- Double-check the Action URL setting"
echo "- Wait 1-2 minutes for changes to propagate"
echo "- Try with a different email address"
echo ""
echo "🎉 Once configured, all password reset emails will use your beautiful template!"
