#!/bin/bash

# Firebase Email Template Setup Script
# This script will help you configure Firebase Auth email templates

echo "🔥 Firebase Email Template Setup Guide"
echo "======================================"
echo ""

echo "📧 STEP 1: Configure Firebase Console Email Templates"
echo "------------------------------------------------------"
echo "1. Go to: https://console.firebase.google.com/"
echo "2. Select your project: swift-26949"
echo "3. Navigate to: Authentication → Templates"
echo "4. Click on 'Password reset' template"
echo "5. Update the following settings:"
echo "   - Subject: 'Reset your ECommerce Admin password'"
echo "   - Sender name: 'ECommerce Admin'"
echo "   - Reply-to: your-support@email.com"
echo ""

echo "🌐 STEP 2: Configure Custom Action URL"
echo "--------------------------------------"
echo "1. In Firebase Console: Authentication → Settings"
echo "2. Click 'Authorized domains' tab"
echo "3. Add your domain if hosting elsewhere"
echo "4. Go to 'Advanced' tab"
echo "5. Set custom action URL to:"
echo "   https://swift-26949.web.app/reset-password"
echo "   OR"
echo "   https://your-custom-domain.com/reset-password"
echo ""

echo "🚀 STEP 3: Deploy Your Beautiful Templates"
echo "------------------------------------------"
echo "Run the following commands:"
echo ""
echo "# Deploy to Firebase Hosting"
echo "firebase deploy --only hosting"
echo ""
echo "# Verify deployment"
echo "firebase hosting:channel:list"
echo ""

echo "✅ STEP 4: Test the Flow"
echo "------------------------"
echo "1. Run your Flutter app"
echo "2. Go to user login screen"
echo "3. Tap 'Forgot Password?'"
echo "4. Enter your email"
echo "5. Check your email for the beautiful template"
echo "6. Click the link to see the custom reset page"
echo ""

echo "🎨 CUSTOMIZATION OPTIONS"
echo "------------------------"
echo "To customize further:"
echo "- Edit: web/email_templates/password_reset.html"
echo "- Edit: web/password_reset.html"
echo "- Update branding, colors, and messaging"
echo "- Deploy again: firebase deploy --only hosting"
echo ""

echo "🔧 TROUBLESHOOTING"
echo "------------------"
echo "If still seeing old templates:"
echo "1. Clear browser cache"
echo "2. Check Firebase Console action URL settings"
echo "3. Verify hosting deployment was successful"
echo "4. Test with a fresh email address"
echo ""

echo "📞 Firebase Console Links:"
echo "- Project: https://console.firebase.google.com/project/swift-26949"
echo "- Auth Templates: https://console.firebase.google.com/project/swift-26949/authentication/emails"
echo "- Hosting: https://console.firebase.google.com/project/swift-26949/hosting"
echo ""

echo "🎉 Once configured, users will receive beautiful emails and see your custom reset page!"
